### Day 3 - Assignment

#### Q1. Create a numpy array starting from 2 till 50 with a stepsize of 3.

In [1]:
import numpy as np

In [2]:
np.array(np.arange(2,50,3))

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47])

#### Q2. Accept two lists of 5 elements each from the user. Convert them to numpy arrays. Concatenate these arrays and print it. Also sort these arrays and print it.

In [21]:
lst1 = []
lst2 = []

def lstentry(lst):
    for i in range(5):
        lst.append(int(input()))
    return lst

print("Enter List 1 : ")
arr1 = np.array(lstentry(lst1))    
print("Enter List 2 : ")
arr2 = np.array(lstentry(lst2))

arr = np.concatenate((arr1, arr2))

print(arr)
print(np.sort(arr))


Enter List 1 : 
5
6
7
8
9
Enter List 2 : 
3
6
0
2
6
[5 6 7 8 9 3 6 0 2 6]
[0 2 3 5 6 6 6 7 8 9]


#### Q3. Write a code snippet to find the dimensions of a ndarray and its size.

In [24]:
ndarr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(ndarr.shape)
print(np.size(ndarr))
print(np.size(ndarr, 0)) 
print(np.size(ndarr, 1))

(2, 4)
8
2
4


#### Q4. How to convert a 1D array into a 2D array? Demonstrate with the help of a code snippet

In [43]:
a = np.array(np.arange(0,9))
print(a,"\n")
b = a.reshape(3,3)
print(b,"\n")

y = a[:, np.newaxis]
print(y.shape)
print(y,"\n")

z = np.expand_dims(a, axis=1)
print(z.shape)
print(z)

[0 1 2 3 4 5 6 7 8] 

[[0 1 2]
 [3 4 5]
 [6 7 8]] 

(9, 1)
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]] 

(9, 1)
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


#### Q5. Consider two square numpy arrays. Stack them vertically and horizontally.

In [59]:
a = np.array(np.arange(4)).reshape(2,2)
b = np.array(np.arange(4,8)).reshape(2,2)
print("\n",np.vstack((a,b)),"\n")
print(np.hstack((a,b)))


 [[0 1]
 [2 3]
 [4 5]
 [6 7]] 

[[0 1 4 5]
 [2 3 6 7]]


#### Q6. How to get unique items and counts of unique items?

In [67]:
lst = np.array([1, 1, 2, 3, 4, 4, 1])

(unique, counts) = np.unique(lst, return_counts=True)
print(np.asarray((unique, counts)).T)

[[1 3]
 [2 1]
 [3 1]
 [4 2]]
